### ISSUE TITLE
我这边redis密码是自定义的，于是使用redis报错

### ISSUE THREAD

**Issue by czh249899518** [Micuks/chatGPT-yunzai#12]
需要在哪里配置redis的密码？

yunzai-bot已经设置过，并且使用是正常的

**Comment by czh249899518** [comment]
Error: Invalid environment; fetch is not defined，还有一个这是啥

**Comment by Micuks** [comment]
你好! 有没有具体的log, 我参考一下寻找一下原因

**Comment by Micuks** [comment]
根据现在的信息, 我认为可能的解决方法是: 如果你使用的 node < 18, 那你需要安装一个 fetch 功能包, 例如`isomorphic-fetch`.

或者考虑升级node到18, 因为node18中, fetch是默认安装的.
