### ISSUE TITLE
与openai通信异常

### ISSUE THREAD

**Issue by 715494637** [Micuks/chatGPT-yunzai#2]
与OpenAI通信异常，请稍后重试：Error: ChatGPT error 404: {
    "error": {
        "message": "That model does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

bot：
[YzBot][23:36:34.454][ERRO] ChatGPTError: ChatGPT error 404: {
    "error": {
        "message": "That model does not exist",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

    at file:///C:/Users/QWQ/Desktop/bot/Yunzai-Bot/node_modules/.pnpm/chatgpt@4.
1.1/node_modules/chatgpt/build/index.js:202:29
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5
) {
  statusCode: 404,
  statusText: 'Not Found',
  [cause]: Response {
    [Symbol(realm)]: null,
    [Symbol(state)]: {
      aborted: false,
      rangeRequested: false,
      timingAllowPassed: true,
      requestIncludesCredentials: true,
      type: 'default',
      status: 404,
      timingInfo: [Object],
      cacheState: '',
      statusText: 'Not Found',
      headersList: [HeadersList],
      urlList: [Array],
      body: [Object]
    },
    [Symbol(headers)]: HeadersList {
      cookies: null,
      [Symbol(headers map)]: [Map],
      [Symbol(headers map sorted)]: null
    }
  }
}

**Comment by Micuks** [comment]
看起来是模型名称没有更新的问题. 可以尝试通过在插件目录下`npm update`或`pnpm update`对chatgpt包进行更新来解决
