### ISSUE TITLE
Having Issue in Deployment

### ISSUE THREAD

**Issue by Musharaf13** [Micuks/chatGPT-yunzai#3]
Hello Micuks.
I forked your repo so that I can get help in using the chatGPT package in my project but I think you are using it in a really advanced way.
Between you could help out here my Issue.
Image attached
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/48816448/220074672-72dc2910-41bf-43af-aaa2-6732b6559cf9.png">

chatGPT response works really well locally but gives this error whenever I'm deploying it on Vercel or Netlify.
here is my repo
https://github.com/Easyfresh-developers/chat_gpt_APIs

Thanking you in anticipation.

**Comment by Micuks** [comment]
Hello, Musharaf13.

By reading the error message, I think maybe you have something wrong in writing an JavaScript module. Maybe somewhere needs a "require", or you can try to rename the file extension name from ".js" to ".cjs" as it suggested in the error message. Read docs about writing javascript modules may also help solving your problem.

I wish my advice could help you!
